version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "annabarnes1138"
    assignees:
      - "annabarnes1138"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    # Group minor and patch updates together to reduce PR noise
    groups:
      vue-ecosystem:
        patterns:
          - "vue*"
          - "@vue/*"
          - "@vitejs/*"
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "annabarnes1138"
    assignees:
      - "annabarnes1138"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"