# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  security:
    name: Security Analysis
    uses: loqalabs/.github/workflows/reusable-security.yml@main
    with:
      language: 'javascript'
      node-version: '20'

  build:
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          fi

      - name: Build
        run: npm run build

      - name: Add CNAME file
        run: echo 'www.loqalabs.com' > dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4