# .github/workflows/deploy.yml
# Test deploy workflow with js-deploy-pages.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write
  security-events: write
  actions: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test:
    name: Test & Build
    uses: loqalabs/.github/.github/workflows/js-test.yml@main
    with:
      node-version: '20'

  security:
    name: Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'javascript'
      node-version: '20'

  deploy:
    name: Deploy to GitHub Pages
    needs: [test, security]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    uses: loqalabs/.github/.github/workflows/js-deploy-pages.yml@main
    with:
      node-version: '20'
      cname: 'www.loqalabs.com'