name: Security Scanning

on:
  schedule:
    # Weekly security scan on Sundays at 1:30 AM UTC
    - cron: '30 1 * * 0'
  workflow_dispatch:

jobs:
  security:
    name: Security Analysis
    uses: loqalabs/.github/.github/workflows/security-scan.yml@main
    with:
      language: 'javascript'
      node-version: '20'
      working-directory: '.'
    secrets: inherit